---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-logging

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: loki-logging-s3
  envs:
  - env-s3

resources:
  - lokistack.yaml
