---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/redhat-cop/gitops-catalog/openshift-logging/operator/overlays/stable
  - github.com/jwennerberg/gitops-catalog/loki-operator/operator/overlays/stable?ref=lokistack
